services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "55000:80"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "55001:80"