name: Basic Build

on:
  pull_request:
    branches:
      - main
      - release*
    paths-ignore:
      - '**/README*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Check Out Repository
        uses: actions/checkout@v4
      - name: 💚 Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: 🧱 Install Dependencies
        run: npm ci
      - name: 📦 Build Application
        run: npm run build
